routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PublicController@index')->name('public.landing');
Route::get('/recipes/{recipe}', 'PublicController@recipe')->name('public.recipe');
Route::post('/search', 'PublicController@search')->name('public.search');

Auth::routes();

Route::resource('/user/recipes', 'RecipesController')->except('create');
Route::resource('/user/units', 'UnitsController')->except('create','show');
Route::resource('/user/ingredients', 'IngredientsController')->except('create','show');

Route::get('/user/recipes/{recipe}/step/{step}', 'RecipesStepsController@edit' )->name('recipes.step.edit');
Route::post('/user/recipes/{recipe}/step', 'RecipesStepsController@store' )->name('recipes.step.add');
Route::put('/user/recipes/{recipe}/step/{step}', 'RecipesStepsController@update' )->name('recipes.step.update');
Route::delete('/user/recipes/{recipe}/step/{step}', 'RecipesStepsController@destroy' )->name('recipes.step.remove');

Route::get('/user/recipes/{recipe}/ingredient/{ingredient}', 'RecipesIngredientsController@edit' )->name('recipes.ingredient.edit');
Route::post('/user/recipes/{recipe}/ingredient', 'RecipesIngredientsController@store' )->name('recipes.ingredient.add');
Route::put('/user/recipes/{recipe}/ingredient/{ingredient}', 'RecipesIngredientsController@update' )->name('recipes.ingredient.update');
Route::delete('/user/recipes/{recipe}/ingredient/{ingredient}', 'RecipesIngredientsController@destroy' )->name('recipes.ingredient.remove');

app/Unit.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Unit extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'unit', 'category'
    ];

    public function ingredients()
    {
        return $this->belongsToMany('App\RecipeIngredient')
            ->withTimestamps();
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function recipes()
    {
        return $this
            ->belongsToMany('App\Recipe')
            ->withTimestamps();
    }
}

app/Http/Controllers/UnitsController.php
<?php

namespace App\Http\Controllers;

use App\Unit;
use Illuminate\Http\Request;

class UnitsController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $units = Unit::latest()->paginate(6);

        return view('user.units.index', compact('units'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Unit  $unit
     * @return \Illuminate\Http\Response
     */
    public function edit(Unit $unit)
    {
        $units = Unit::latest()->paginate(6);

        return view('user.units.index', compact('unit', 'units'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     * @throws \Exception
     */
    public function store(Request $request)
    {
        request()->validate([
            'name' => 'required|string|max:255',
            'unit' => 'required|string|max:255]unique:units,unit',
            'group' => 'required'
        ]);

        $unit = new Unit;
        if(isset($request->name)){ $unit->name = strtolower($request->name);}
        if(isset($request->unit)){ $unit->unit = strtolower($request->unit);}
        if(isset($request->group)){ $unit->group = strtolower($request->group);}
        $unit->save();

        return redirect()->back()->with('success', 'Unit successfully created');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Unit  $unit
     * @return \Illuminate\Http\Response
     * @throws \Exception
     */
    public function update(Request $request, Unit $unit)
    {
        request()->validate([
            'name' => 'required|string|max:255',
            'unit' => 'required|string|max:255]unique:units,unit',
            'group' => 'required'
        ]);

        if($unit->name !== strtolower($request->name)){
            $unit->name = strtolower($request->name);
        }
        if($unit->unit !== strtolower($request->unit)){
            $unit->unit = strtolower($request->unit);
        }
        if($unit->group !== strtolower($request->group)){
            $unit->group = strtolower($request->group);
        }
        $unit->update();

        return redirect()->route('units.index')->with('success', 'Unit updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Unit $unit
     * @return \Illuminate\Http\Response
     * @throws \Exception
     */
    public function destroy(Unit $unit)
    {
        $unit->delete();
        return redirect()->back()->with('success', 'Unit deleted successfully');
    }
}

resources/views/user/units/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        <div class="row">

            @include('incl.user-menu')

            <div class="col-sm-12 col-md-8 col-lg-10">

                @if ($message = Session::get('success'))
                    <div class="alert alert-success mb-4">
                        <p>{{ $message }}</p>
                    </div>
                @endif

                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif

                    <div class="card mb-4">
                        @if(isset($unit))
                            <div class="card-header">Edit unit</div>
                            <div class="card-body">
                                <form action="{{route('units.update', $unit->id)}}" method="POST">
                                    @method('PUT')
                                    @csrf

                                    @include('forms.units')
                                    <div class="text-right">
                                        <input type="submit" class="btn btn-sm btn-primary" value="Edit">
                                    </div>
                                </form>
                            </div>
                        @else
                            <div class="card-header">Create unit</div>
                            <div class="card-body">
                                <form action="{{ route('units.store') }}" method="POST">
                                    @csrf

                                    @include('forms.units')
                                    <div class="text-right">
                                        <input type="submit" class="btn btn-sm btn-primary" value="Create">
                                    </div>
                                </form>
                            </div>
                        @endif
                    </div>


                <div class="card mb-4">
                    <div class="card-header">All measurements units</div>
                    <div class="card-body">
                        <table class="table table-sm">
                            <thead>
                            <tr>
                                <th scope="col" width="120">#</th>
                                <th scope="col" width="120">unit</th>
                                <th scope="col">Name</th>
                                @if(Auth::user()->admin === 1)
                                    <th scope="col" width="120" class="text-center">Controls</th>
                                @endif
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($units as $single_unit)
                                <tr>
                                    <th scope="row">{{$single_unit->id  }}</th>
                                    <td>{{ ucfirst($single_unit->unit) }}</td>
                                    <td>{{ ucfirst($single_unit->name) }}</td>
                                    @if(Auth::user()->admin === 1)
                                    <td>
                                        <form action="{{ route('units.destroy', $single_unit->id) }}" method="POST" class="btn-group-sm text-center">
                                            <a href="{{ route('units.edit', $single_unit->id) }}" class="btn btn-outline-dark">Edit</a>
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class="btn btn-outline-danger btn-delete">Delete</button>
                                        </form>
                                    </td>
                                    @endif
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                        {{ $units->links() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection