routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PublicController@index')->name('public.landing');
Route::get('/recipes/{recipe}', 'PublicController@recipe')->name('public.recipe');
Route::post('/search', 'PublicController@search')->name('public.search');

Auth::routes();

Route::resource('/user/recipes', 'RecipesController')->except('create');
Route::resource('/user/units', 'UnitsController')->except('create','show');
Route::resource('/user/ingredients', 'IngredientsController')->except('create','show');

Route::get('/user/recipes/{recipe}/step/{step}', 'RecipesStepsController@edit' )->name('recipes.step.edit');
Route::post('/user/recipes/{recipe}/step', 'RecipesStepsController@store' )->name('recipes.step.add');
Route::put('/user/recipes/{recipe}/step/{step}', 'RecipesStepsController@update' )->name('recipes.step.update');
Route::delete('/user/recipes/{recipe}/step/{step}', 'RecipesStepsController@destroy' )->name('recipes.step.remove');

Route::get('/user/recipes/{recipe}/ingredient/{ingredient}', 'RecipesIngredientsController@edit' )->name('recipes.ingredient.edit');
Route::post('/user/recipes/{recipe}/ingredient', 'RecipesIngredientsController@store' )->name('recipes.ingredient.add');
Route::put('/user/recipes/{recipe}/ingredient/{ingredient}', 'RecipesIngredientsController@update' )->name('recipes.ingredient.update');
Route::delete('/user/recipes/{recipe}/ingredient/{ingredient}', 'RecipesIngredientsController@destroy' )->name('recipes.ingredient.remove');

app/Ingredient.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Ingredient extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name'
    ];

    public function recipesIngredients()
    {
        return $this
            ->belongsToMany('App\RecipeIngredients')
            ->withTimestamps();
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function recipes()
    {
        return $this
            ->belongsToMany('App\Recipe')
            ->withTimestamps();
    }
}

app/Http/Controllers/IngredientsController.php
<?php

namespace App\Http\Controllers;

use App\Ingredient;
use Illuminate\Http\Request;

class IngredientsController extends Controller
{

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $ingredients = Ingredient::latest()->paginate(8);

        return view('user.ingredients.index', compact('ingredients'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Ingredient  $ingredient
     * @return \Illuminate\Http\Response
     */
    public function edit(Ingredient $ingredient)
    {
        $ingredients = Ingredient::latest()->orderBy('name')->paginate(10);
        return view('user.ingredients.index', compact('ingredient', 'ingredients'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     * @throws \Exception
     */
    public function store(Request $request)
    {
        request()->validate([
            'name' => 'required|string|max:255'
        ]);

            $newIngredient = new Ingredient;

            if(isset($request->name)){
                $newIngredient->name = strtolower($request->name);
                $newIngredient->save();
            }

        return redirect()->back()->with('success', 'Ingredient was created successfully');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Ingredient  $ingredient
     * @return \Illuminate\Http\Response
     * @throws \Exception
     */
    public function update(Request $request, Ingredient $ingredient)
    {
        request()->validate([
            'name' => 'required|string|max:255'
        ]);

        if(isset($request->name) && $ingredient->name !== strtolower($request->name)){
            $ingredient->name = strtolower($request->name);
            $ingredient->update();
        }

        return redirect()->route('units.index')->with('success', 'Ingredient updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Ingredient $ingredient
     * @return \Illuminate\Http\Response
     * @throws \Exception
     */
    public function destroy(Ingredient $ingredient)
    {

        $ingredient->delete();
        return redirect()->back()->with('success', 'Ingredient deleted successfully');
    }
}

resources/views/user/ingredients/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        <div class="row">

            @include('incl.user-menu')

            <div class="col-sm-12 col-md-8 col-lg-10">

                @if ($message = Session::get('success'))
                    <div class="alert alert-success mb-4">
                        <p>{{ $message }}</p>
                    </div>
                @endif

                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif

                <div class="card mb-4">
                    @if(isset($ingredient))
                        <div class="card-header">Edit ingredient</div>
                        <div class="card-body">
                            <form action="{{route('ingredients.update', $ingredient->id)}}" method="POST">
                            @method('PUT')
                            @csrf

                            @include('forms.ingredients')
                                <div class="text-right">
                                    <input type="submit" class="btn btn-sm btn-primary" value="Edit">
                                </div>
                            </form>
                        </div>
                    @else
                        <div class="card-header">Create ingredient</div>
                        <div class="card-body">
                            <form action="{{ route('ingredients.store') }}" method="POST">
                            @csrf

                            @include('forms.ingredients')
                                <div class="text-right">
                                    <input type="submit" class="btn btn-sm btn-primary" value="Create">
                                </div>
                            </form>
                        </div>
                    @endif
                </div>

                <div class="card mb-4">
                    <div class="card-header">All ingredients</div>
                    <div class="card-body">
                        <table class="table table-sm">
                            <thead>
                            <tr>
                                <th scope="col" width="50">#</th>
                                <th scope="col">Name</th>
                                <th scope="col" width="120" class="text-center">Controls</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($ingredients as $single_ingredient)
                                <tr>
                                    <th scope="row">{{$single_ingredient->id  }}</th>
                                    <td>{{ ucfirst($single_ingredient->name) }}</td>
                                    <td>
                                        @if(Auth::user()->admin === 1)
                                        <form action="{{ route('ingredients.destroy', $single_ingredient->id) }}" method="POST" class="btn-group-sm text-center">
                                            <a href="{{ route('ingredients.edit', $single_ingredient->id) }}" class="btn btn-outline-dark">Edit</a>
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class="btn btn-outline-danger btn-delete">Delete</button>
                                        </form>
                                        @endif
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                        {{ $ingredients->links() }}
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection