routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PublicController@index')->name('public.landing');
Route::get('/recipes/{recipe}', 'PublicController@recipe')->name('public.recipe');
Route::post('/search', 'PublicController@search')->name('public.search');

Auth::routes();

Route::resource('/user/recipes', 'RecipesController')->except('create');
Route::resource('/user/units', 'UnitsController')->except('create','show');
Route::resource('/user/ingredients', 'IngredientsController')->except('create','show');

Route::get('/user/recipes/{recipe}/step/{step}', 'RecipesStepsController@edit' )->name('recipes.step.edit');
Route::post('/user/recipes/{recipe}/step', 'RecipesStepsController@store' )->name('recipes.step.add');
Route::put('/user/recipes/{recipe}/step/{step}', 'RecipesStepsController@update' )->name('recipes.step.update');
Route::delete('/user/recipes/{recipe}/step/{step}', 'RecipesStepsController@destroy' )->name('recipes.step.remove');

Route::get('/user/recipes/{recipe}/ingredient/{ingredient}', 'RecipesIngredientsController@edit' )->name('recipes.ingredient.edit');
Route::post('/user/recipes/{recipe}/ingredient', 'RecipesIngredientsController@store' )->name('recipes.ingredient.add');
Route::put('/user/recipes/{recipe}/ingredient/{ingredient}', 'RecipesIngredientsController@update' )->name('recipes.ingredient.update');
Route::delete('/user/recipes/{recipe}/ingredient/{ingredient}', 'RecipesIngredientsController@destroy' )->name('recipes.ingredient.remove');

resources/views/incl/nav.blade.php
<nav class="navbar navbar-expand-md navbar-light navbar-laravel">
    <div class="container-fluid">
        <a class="navbar-brand" href="{{ url('/') }}">
            {{ config('app.name', 'Laravel') }}
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <!-- Left Side Of Navbar -->
            <ul class="navbar-nav mr-auto">

            </ul>

            <!-- Right Side Of Navbar -->
            <ul class="navbar-nav ml-auto">
                <li><a href="{{ route('public.landing') }}" class="nav-link">Homepage</a></li>
                <!-- Authentication Links -->
                @guest
                    <li><a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a></li>
                    <li><a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a></li>
                @else
                    <li class="nav-item dropdown">
                        <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                            {{ Auth::user()->name }} <span class="caret"></span>
                        </a>

                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a href="{{route('recipes.index')}}" class="dropdown-item">{{ __('Dashboard') }}</a>

                            <a class="dropdown-item" href="{{ route('logout') }}"
                               onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                {{ __('Logout') }}
                            </a>

                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                @csrf
                            </form>
                        </div>
                    </li>
                @endguest
            </ul>
        </div>
    </div>
</nav>

resources/views/incl/user-menu.blade.php
<div class="col-sm-12 col-md-4 col-lg-2">
    <div class="card">
        <div class="card-header">Menu</div>

        <div class="card-body">
            <ul class="nav flex-column">
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('recipes.index') }}">Recipes</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('ingredients.index') }}">Ingredients</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('units.index') }}">Units</a>
                </li>
            </ul>
        </div>
    </div>
</div>