routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'PublicController@index')->name('public.landing');
Route::get('/recipes/{recipe}', 'PublicController@recipe')->name('public.recipe');
Route::post('/search', 'PublicController@search')->name('public.search');

Auth::routes();

Route::resource('/user/recipes', 'RecipesController')->except('create');
Route::resource('/user/units', 'UnitsController')->except('create','show');
Route::resource('/user/ingredients', 'IngredientsController')->except('create','show');

Route::get('/user/recipes/{recipe}/step/{step}', 'RecipesStepsController@edit' )->name('recipes.step.edit');
Route::post('/user/recipes/{recipe}/step', 'RecipesStepsController@store' )->name('recipes.step.add');
Route::put('/user/recipes/{recipe}/step/{step}', 'RecipesStepsController@update' )->name('recipes.step.update');
Route::delete('/user/recipes/{recipe}/step/{step}', 'RecipesStepsController@destroy' )->name('recipes.step.remove');

Route::get('/user/recipes/{recipe}/ingredient/{ingredient}', 'RecipesIngredientsController@edit' )->name('recipes.ingredient.edit');
Route::post('/user/recipes/{recipe}/ingredient', 'RecipesIngredientsController@store' )->name('recipes.ingredient.add');
Route::put('/user/recipes/{recipe}/ingredient/{ingredient}', 'RecipesIngredientsController@update' )->name('recipes.ingredient.update');
Route::delete('/user/recipes/{recipe}/ingredient/{ingredient}', 'RecipesIngredientsController@destroy' )->name('recipes.ingredient.remove');

app/Recipe.php
<?php

namespace App;

use Laravel\Scout\Searchable;
use Illuminate\Database\Eloquent\Model;

class Recipe extends Model
{
    use Searchable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'title', 'desc', 'image'
    ];

    public function users()
    {
        return $this
            ->belongsToMany('App\User')
            ->withTimestamps();
    }

    public function recipeSteps()
    {
        return $this
            ->hasMany('App\recipeStep');
    }

    public function recipeIngredients()
    {
        return $this
            ->hasMany('App\recipeIngredient');
    }

    public function hasIngredients($tagToMatch)
    {
        foreach ($this->recipeIngredients->ingredients as $ingredient)
        {
            if ($ingredient->id == $tagToMatch)
                return (true);
        }
        return (false);
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function recipes()
    {
        return $this
            ->belongsToMany('App\Recipe')
            ->withTimestamps();
    }
}

app/Http/Controllers/RecipesController.php
<?php

namespace App\Http\Controllers;

use App\Ingredient;
use App\Recipe;
use App\Unit;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;

class RecipesController extends Controller
{

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }


    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $recipes = Auth::user()->admin != true ? Auth::user()->recipes->paginate(5) : Recipe::latest()->paginate(5);
        return view('user.recipes.index', compact('recipes'));
    }


    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        request()->validate([
            'title' => 'required|string|max:255',
            'desc' => 'required'
        ]);

        $recipe = new Recipe;

        if(isset($request->title)){ $recipe->title = strtolower($request->title); }
        if(isset($request->desc)){ $recipe->desc = strtolower($request->desc); }
        if($request->hasFile('image')){
            $recipe->image = $request->image->store('public');
        }

        $recipe->save();

        Auth::user()->recipes()->attach($recipe->id);

        return redirect()->route('recipes.show', $recipe->id)
            ->with('success','Recipe created successfully');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Recipe  $recipe
     * @return \Illuminate\Http\Response
     */
    public function show(Recipe $recipe)
    {
        $ingredientsList = Ingredient::all();
        $unitsList = Unit::all();

        return view('user.recipes.show', compact('recipe', 'ingredientsList', 'unitsList'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Recipe  $recipe
     * @return \Illuminate\Http\Response
     */
    public function edit(Recipe $recipe)
    {
        $ingredientsList = Ingredient::all();
        $unitsList = Unit::all();

        return view('user.recipes.show', compact('recipe','ingredientsList', 'unitsList'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Recipe  $recipe
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Recipe $recipe)
    {
        request()->validate([
            'title' => 'required|string|max:255',
            'desc' => 'required',
        ]);

        if($recipe->title !== strtolower($request->title)){
            $recipe->title = strtolower($request->title);
        }

        if($recipe->desc !== strtolower($request->desc)){
            $recipe->desc = strtolower($request->desc);
        }

        if($request->hasFile('image')){
            Storage::delete($recipe->image);
            $recipe->image = $request->image->store('public');
        }

        $recipe->update();

        return redirect()->route('recipes.index')
            ->with('success','Recipe updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Recipe $recipe
     * @return \Illuminate\Http\Response
     * @throws \Exception
     */
    public function destroy(Recipe $recipe)
    {

        if($recipe->ingredients !== null){
            foreach($recipe->ingredients as $ingredient)
            {
                $recipe->ingredients()->detach($ingredient->id);
            }
        }

        if($recipe->steps !== null){
            foreach($recipe->steps as $step)
            {
                $recipe->steps()->delete($step->id);
            }
        }

        if($recipe->image !== null){
            Storage::delete($recipe->image);
        }


        $user = User::find(Auth::user()->id);

        if($user !== null){
            $user->recipes()->detach($recipe->id);
        }

        $recipe->delete();

        return redirect()->route('recipes.index')
            ->with('success','Recipe and image deleted successfully');
    }
}

resources/views/user/recipes/edit.blade.php
@extends('layouts.app')

@section('content')

    <div class="container-fluid">
        <div class="row">

            @include('incl.user-menu')

            <div class="col-sm-12 col-md-8 col-lg-10">

                @if ($message = Session::get('success'))
                    <div class="alert alert-success mb-4">
                        <p>{{ $message }}</p>
                    </div>
                @endif

                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif

                <div class="card mb-4">
                    <div class="card-header">Edit {{isset($recipeIngredient)? 'ingredient' : 'step'}}</div>
                    <div class="card-body">

                        @if(isset($recipe) && isset($recipeIngredient))

                            <form action="{{route('recipes.ingredient.update', [$recipe->id, $recipeIngredient->id])}}" method="POST">
                                @csrf
                                @method('PUT')
                                @include('forms.recipesIngredients')
                                <div class="d-flex justify-content-between">
                                    <a href="{{ route('recipes.edit' , $recipe->id) }}" class="btn btn-sm btn-danger">Go back</a>
                                    <button type="submit" class="btn btn-sm btn-primary">Update</button>
                                </div>
                            </form>

                        @elseif(isset($recipe) && isset($step))

                            <form action="{{route('recipes.step.update', [$recipe->id, $step->id])}}" method="POST">
                                @csrf
                                @method('PUT')
                                @include('forms.recipesSteps')
                                <div class="d-flex justify-content-between">
                                    <a href="{{ route('recipes.edit' , $recipe->id) }}" class="btn btn-sm btn-danger">Go back</a>
                                    <button type="submit" class="btn btn-sm btn-primary">Update</button>
                                </div>
                            </form>
                        @endif
                    </div>
                </div>
            </div>
        </div>
@endsection

resources/views/user/recipes/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
    <div class="row">

        @include('incl.user-menu')

        <div class="col-sm-12 col-md-8 col-lg-10">
        @if(session('status') or session('login'))
            <div class="card mb-4">
                <div class="card-header">Dashboard</div>
                <div class="card-body">
                @if (session('status'))
                    <div class="alert alert-success">
                        {{ session('status') }}
                    </div>
                @endif

                @if(session('login'))
                    <p>You are logged in!</p>
                @endif
                </div>
            </div>
        @endif

            @if ($message = Session::get('success'))
                <div class="alert alert-success mb-4">
                    <p>{{ $message }}</p>
                </div>
            @endif

            @if ($errors->any())
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif

            <div class="card mb-4">
                <div class="card-header">Create Recipe</div>
                <div class="card-body">
                    <form action="{{ route('recipes.store') }}" method="POST" enctype="multipart/form-data">
                        @csrf
                        @include('forms.recipes')

                        <div class="text-right">
                            <input type="submit" class="btn btn-sm btn-primary" value="Create">
                        </div>
                    </form>
                </div>
            </div>

            <div class="card mb-4">
                <div class="card-header">All Recipes</div>
                <div class="card-body">
                    <table class="table table-sm">
                        <thead>
                        <tr>
                            <th scope="col" width="50">#</th>
                            <th scope="col" width="100">Image</th>
                            <th scope="col">Title</th>
                            <th scope="col">Desc</th>
                            <th scope="col" width="150">Controls</th>
                        </tr>
                        </thead>
                        <tbody>

                    @foreach($recipes as $recipe)
                        <tr>
                            <th scope="row">{{ $recipe->id }}</th>
                            <td><img src="{{ Storage::disk('local')->url($recipe->image) }}" alt="..." class="img-thumbnail"/></td>
                            <td>{{ $recipe->title }}</td>
                            <td>{{ $recipe->desc }}</td>
                            <td>
                                <form action="{{ route('recipes.destroy', $recipe->id) }}" method="POST" class="btn-group-sm">
                                    @csrf
                                    @method('DELETE')
                                    <a href="{{ route('recipes.show', $recipe->id) }}" class="btn btn-outline-dark">Details</a>
                                    <button type="submit" class="btn btn-outline-danger btn-delete">Delete</button>
                                </form>
                            </td>
                        </tr>
                    @endforeach

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/user/recipes/show.blade.php
@extends('layouts.app')

@section('content')

    <div class="container-fluid">
        <div class="row">

            @include('incl.user-menu')

            <div class="col-sm-12 col-md-8 col-lg-10">

                @if ($message = Session::get('success'))
                    <div class="alert alert-success mb-4">
                        <p>{{ $message }}</p>
                    </div>
                @endif

                @if ($errors->any())
                    <div class="alert alert-danger">
                        <ul>
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif

                <div class="card mb-4">
                    <div class="card-header">Recipe Details</div>
                    <div class="card-body">
                        <form action="{{route('recipes.update', $recipe->id)}}" method="POST" enctype="multipart/form-data">
                            @method('PUT')
                            @csrf
                            @include('forms.recipes')

                            <div class="text-right">
                                <button type="submit" class="btn btn-sm btn-primary">Update</button>
                            </div>
                        </form>
                    </div>
                </div>



                <div class="card mb-4">
                    <div class="card-header">Add Ingredients</div>
                    <div class="card-body">
                        <form action="{{route('recipes.ingredient.add', $recipe->id)}}" method="POST">
                        @csrf
                        @include('forms.recipesIngredients')
                            <div class="text-right">
                                <button type="submit" class="btn btn-sm btn-primary">Add Ingredient</button>
                            </div>
                        </form>
                    </div>
                </div>


                <div class="card mb-4">
                    <div class="card-header">Recipe Ingredients</div>
                    <div class="card-body">
                        <table class="table table-sm">
                            <thead>
                            <tr>
                                <th scope="col" width="150">Quantity</th>
                                <th scope="col" width="150">Measurements</th>
                                <th scope="col">Ingredient</th>
                                <th scope="col" width="120">controls</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($recipe->recipeIngredients as $recipeIngredient)
                                <tr>
                                    <td>{{$recipeIngredient->amount}}</td>
                                    <td>
                                        @foreach($recipeIngredient->units as $unit)
                                            {{$unit->unit}} / {{$unit->name}}
                                        @endforeach
                                    </td>
                                    <td>
                                        @foreach($recipeIngredient->ingredients as $ingredient)
                                            {{$ingredient->name}}
                                        @endforeach
                                    </td>
                                    <td>
                                        <form action="{{ route('recipes.ingredient.remove', [$recipe->id, $recipeIngredient->id]) }}" method="POST" class="btn-group-sm">
                                            @csrf
                                            @method('DELETE')
                                            <a href="{{ route('recipes.ingredient.edit', [$recipe->id, $recipeIngredient->id]) }}" class="btn btn-outline-dark">Edit</a>
                                            <button type="submit" class="btn btn-outline-danger btn-delete">Delete</button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>


                <div class="card mb-4">
                    <div class="card-header">Add Steps</div>
                    <div class="card-body">
                        <form action="{{route('recipes.step.add', $recipe->id)}}" method="POST">
                            @csrf
                            @include('forms.recipesSteps')
                            <div class="text-right">
                                <button type="submit" class="btn btn-sm btn-primary">Add Steps</button>
                            </div>
                        </form>
                    </div>
                </div>


                <div class="card mb-4">
                    <div class="card-header">Recipe Steps</div>
                    <div class="card-body">
                        <table class="table table-sm">
                            <thead>
                            <tr>
                                <th scope="col" width="50">#</th>
                                <th scope="col">Desc</th>
                                <th scope="col" width="120">controls</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($recipe->recipeSteps as $step)
                                <tr>
                                    <td>{{ $step->step_number }}</td>
                                    <td>{{ $step->instructions }}</td>
                                    <td>
                                        <form action="{{ route('recipes.step.remove', [$recipe->id, $step->id]) }}" method="POST" class="btn-group-sm">
                                            @csrf
                                            @method('DELETE')
                                            <a href="{{ route('recipes.step.edit', [$recipe->id, $step->id]) }}" class="btn btn-outline-dark">Edit</a>
                                            <button type="submit" class="btn btn-outline-danger btn-delete">Delete</button>
                                        </form>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
@endsection